### PR TITLE
Fix type error in LoggerAdapter constructor

### LINKED ISSUE #36: TypeError: __init__() missing 1 required positional argument: 'extra'
The `EODMSLogger` constructor raises a type error when using a python version `<=3.9`. From the [`setup.cfg`](https://github.com/eodms-sgdot/py-eodms-dds/blob/main/setup.cfg) I can see we want `eodms-dds` to support `python_requires='>=3.7'`.

The type error is caused by the `extra` parameter of the `LoggerAdapter` being required for earlier python versions:

- In [v3.9](https://github.com/python/cpython/releases/tag/v3.9.23) The `extra` parameter is required: https://github.com/python/cpython/blob/88663ef89ba3576df02cc818c653f91c7d5dd023/Lib/logging/__init__.py#L1801
- In [v3.10](https://github.com/python/cpython/releases/tag/v3.10.18) the `extra=None` parameter is optional: https://github.com/python/cpython/blob/865270262ade38b96fce88e32a321caac5332a87/Lib/logging/__init__.py#L1766

### PR DESCRIPTION
**Pull request by LeapSeconds**
Resolves https://github.com/eodms-sgdot/py-eodms-dds/issues/36

(sorry for the regression caused by https://github.com/eodms-sgdot/py-eodms-dds/pull/30)

### CODE REVIEW

**Comment by LeapSeconds** [comment]
Closing the change was made here -> https://github.com/eodms-sgdot/py-eodms-dds/commit/8493a3c1ef1092d357ca47bc2342f8d8fc702ced
